### ISSUE TITLE
Traceback Error: Started Since Update

### ISSUE THREAD

**Issue by EternalDeviant** [Avnsx/fansly-downloader#108]
I am getting the following error for what seems to be m3u8 (video) filetypes. Stops the script and asks to press enter to continue and will download images until it hits the next video.

 Info | 08:03 || Executing Timeline functionality. Anticipate remarkable outcomes!

 Info | 08:03 || Inspecting most recent Timeline cursor
 Info | 08:03 || Amount of Media in current cursor: 24 (scrapable: 24)
 Info | 08:03 || Downloading image '2023-06-14_at_17-32_id_525403681718284288.jpeg'
 Info | 08:03 || Downloading image '2023-06-14_at_17-32_id_525403556098875392.jpeg'
 Info | 08:03 || Deduplication [Media ID]: image '2023-06-13_at_02-29_id_524813906934243328.jpeg' → declined
 Info | 08:03 || Deduplication [Media ID]: image '2023-06-13_at_02-29_id_524813905071972352.jpeg' → declined
 Info | 08:03 || Deduplication [Media ID]: image '2023-06-12_at_02-04_id_524445403827937280.jpeg' → declined
 Info | 08:03 || Deduplication [Media ID]: image '2023-06-12_at_02-04_id_524445403471421440.jpeg' → declined
 Info | 08:03 || Deduplication [Media ID]: image '2023-06-11_at_17-54_id_524322057513611264.jpeg' → declined
 Info | 08:03 || Deduplication [Media ID]: image '2023-06-11_at_17-54_id_524322007374897152.jpeg' → declined
 Info | 08:03 || Deduplication [Media ID]: video '2023-06-10_at_03-28_id_523560480489349120.m3u8' → declined

 **Info | 08:03 || Downloading video '2023-06-10_at_03-26_id_523559644438736896.m3u8'
Could not detect TS packet size, defaulting to non-FEC/DVHS

 [33]ERROR | 08:03 || Unexpected error during sorting Timeline download:
Traceback (most recent call last):
  File "fansly_downloader.py", line 1415, in <module>
  File "fansly_downloader.py", line 737, in sort_download
  File "fansly_downloader.py", line 614, in download_m3u8
IndexError: tuple index out of range

 Press Enter to attempt to continue ..**

 Info | 08:03 || Inspecting Timeline cursor: 523474580535255040
 Info | 08:03 || Amount of Media in current cursor: 44 (scrapable: 44)
 Info | 08:03 || Downloading image '2023-06-09_at_09-46_id_523474429804552192.jpeg'
 Info | 08:03 || Downloading image '2023-06-09_at_09-46_id_523474429393510400.jpeg'
 Info | 08:03 || Downloading image '2023-06-09_at_09-46_id_523474419012608001.jpeg'
 Info | 08:03 || Downloading image '2023-06-09_at_09-45_id_523474201831550976.jpeg'

**Comment by Avnsx** [comment]
What creator is this happening with

**Comment by Avnsx** [comment]
Unable to reproduce the bug, as the media causing errors appears to be restricted to subscribers only.
To assist in resolving the issue, kindly send an email to ``AvnDev@protonmail.com`` with account credentials, which have access to the mentioned content.

**Comment by CaptainKoons** [comment]
I think I have the same issue.
Many thanks in advance!


 Info | 09:03 || Downloading video '2023-05-04_at_16-04_id_510507080679956480.m3u8'
start time for stream 1 is not set in estimate_timings_from_pts
stream 1 : no TS found at start of file, duration not set
Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
start time for stream 1 is not set in estimate_timings_from_pts
stream 1 : no TS found at start of file, duration not set
Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
sample rate not set

 [33]ERROR | 09:03 || Unexpected error during sorting Timeline download:
Traceback (most recent call last):
  File "fansly_downloader.py", line 1415, in <module>
  File "fansly_downloader.py", line 737, in sort_download
  File "fansly_downloader.py", line 631, in download_m3u8
  File "av\container\output.pyx", line 203, in av.container.output.OutputContainer.mux
  File "av\container\output.pyx", line 209, in av.container.output.OutputContainer.mux_one
  File "av\container\output.pyx", line 175, in av.container.output.OutputContainer.start_encoding
  File "av\container\core.pyx", line 292, in av.container.core.Container.err_check
  File "av\error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'L:\\***\\Timeline\\Videos\\2023-05-04_at_16-04_id_510507080679956480.mp4'; last error log: [mp4] sample rate not set


 Press Enter to attempt to continue ..

**Comment by Avnsx** [comment]
@EternalDeviant @CaptainKoons I have made several commits that address this issue. Please download the [latest python version](https://github.com/Avnsx/fansly-downloader#python-version-requirements) of the repository and let me know if those changes, solve the issue you were having before.
