### ISSUE TITLE
M3U8 Download failed "start time for stream 1 is not set in estimate_timings_from_pts"

### ISSUE THREAD

**Issue by Avnsx** [Avnsx/fansly-downloader#110]
I think I have the same issue.

Download in normal mode:

>  Info | 09:03 || Downloading video '2023-05-04_at_16-04_id_510507080679956480.m3u8'
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> sample rate not set
> 
>  [33]ERROR | 09:03 || Unexpected error during sorting Timeline download:
> Traceback (most recent call last):
>   File "fansly_downloader.py", line 1415, in <module>
>   File "fansly_downloader.py", line 737, in sort_download
>   File "fansly_downloader.py", line 631, in download_m3u8
>   File "av\container\output.pyx", line 203, in av.container.output.OutputContainer.mux
>   File "av\container\output.pyx", line 209, in av.container.output.OutputContainer.mux_one
>   File "av\container\output.pyx", line 175, in av.container.output.OutputContainer.start_encoding
>   File "av\container\core.pyx", line 292, in av.container.core.Container.err_check
>   File "av\error.pyx", line 336, in av.error.err_check
> av.error.ValueError: [Errno 22] Invalid argument: 'L:\\***\\Timeline\\Videos\\2023-05-04_at_16-04_id_510507080679956480.mp4'; last error log: [mp4] sample rate not set
> 
> 
>  Press Enter to attempt to continue ..
> 

After pressing enter the scrapping continues but skips some posts.

I tried to scrap these posts with single mode, and most of them worked.

But the above mentioned post had still some isses in single mode. It downloaded a big video file (4,1GB) but the audio & playback speed was broken, and I got the following error massage multiple times:

>                 ► Post ID: 510503212856389632
>  Info | 10:42 || Inspecting a post by Tsbellabates
>  Info | 10:42 || Amount of Media linked to Single post: 1 (scrapable: 1)
>  Info | 10:42 || Downloading video '2023-05-04_at_16-38_id_510501568424980480.m3u8'
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> start time for stream 1 is not set in estimate_timings_from_pts
> *
> *
> *
> *
> *
> *
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> 
> ╔═
>   Finished Single type, download of 0 pictures & 1 videos! Declined duplicates: 0
>   Saved content in directory: 'L:\***'
>   ✶ Please leave a Star on the GitHub Repository, if you are satisfied! ✶
>                                                                           ═╝
> 
>  Press Enter to close ..
> 

A second post with 3 shorts videos (~2min) + 1 pic didn't work either in single mode. I got the following error massage:

>  Info | 10:35 || Amount of Media linked to Single post: 4 (scrapable: 4)
>  Info | 10:35 || Downloading video '2023-05-04_at_16-05_id_510507960833679360.m3u8'
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> sample rate not set
> 
>  [19]ERROR | 10:35 || Unexpected error during sorting Single Post download;
> Traceback (most recent call last):
>   File "fansly_downloader.py", line 1168, in <module>
>   File "fansly_downloader.py", line 737, in sort_download
>   File "fansly_downloader.py", line 631, in download_m3u8
>   File "av\container\output.pyx", line 203, in av.container.output.OutputContainer.mux
>   File "av\container\output.pyx", line 209, in av.container.output.OutputContainer.mux_one
>   File "av\container\output.pyx", line 175, in av.container.output.OutputContainer.start_encoding
>   File "av\container\core.pyx", line 292, in av.container.core.Container.err_check
>   File "av\error.pyx", line 336, in av.error.err_check
> av.error.ValueError: [Errno 22] Invalid argument: 'L:\\***\\Videos\\2023-05-04_at_16-05_id_510507960833679360.mp4'; last error log: [mp4] sample rate not set
> 
> 
>  Press Enter to attempt to continue ..

It may be coincidence or not, but both of the posts which are not working (even in single mode) got posted on the same date (2023/05/04). And the 3 smaller videos from the one post are teasers from the big video in the other post.

Many thanks in advance!

BR, CK

_Originally posted by @CaptainKoons in https://github.com/Avnsx/fansly-downloader/issues/108#issuecomment-1595652928_

**Comment by Avnsx** [comment]
@CaptainKoons This is different error, then the guy got in the other issue ticket.

Also I knew about this specific error where it says something about ``estimate_timings_from_pts`` before already and usually this does not influence the output media in any way. It just prints the warning into the console and that's about it.

I think the media that has the "playback speed" issues that you mentioned is the media that also errors out saying ``"av.error.ValueError"``. I am not sure if the estimate_timings_from_pts thing and the ValueError are even coherent to each other.

Regardless I am unable to reproduce the bug, as all of the mentioned media causing those errors appears to be restricted to subscribers only. To assist in resolving the issue, kindly send an email to ``AvnDev@protonmail.com`` with account credentials, which have access to the mentioned content.

**Comment by Avnsx** [comment]
@CaptainKoons I have made several commits that address this issue. Please download the [latest python version](https://github.com/Avnsx/fansly-downloader#python-version-requirements) of the repository and let me know if those changes, solve the issue you were having before.

**Comment by CaptainKoons** [comment]
@Avnsx  I’ve tried the latest python version as you said. 
And it worked perfectly fine with single post download on the long 4gb+ video post! (I haven’t tied a full scrap)
Many thanks for that already!!! 🍻

But the second error post with the 3 smaller videos+1pic still gets an error. In my particular case its not an issues because, as I mentioned, these 3 videos are only snippets from the longer one which I have been able to download now. But maybe you would like to look into it anyway. 

I got the following feedback from the app:

> Info | 16:19 || Reading config.ini file ...
> 
>  info | 16:19 || Username validation successful!
> 
>  WARNING | 16:19 || Due to the presence of 'Pictures' and 'Videos' sub-directories in the current download folder;      
>                     content separation will remain disabled throughout this current downloading session.
>  Info | 16:19 || Deduplication is automatically enabled for;
>                  C:\Users\***\Videos\fansly-downloader_test\tsbellabates_fansly
>  Info | 16:19 || Deduplication process is complete! Each new download will now be compared
>                  against a total of 0 photo & 0 video hashes and corresponding media IDs.
>  Info | 16:19 || Using user-agent: 'Mozilla/5.0 (Windows NT 10.0 [...] 109.0) Gecko/20100101 Firefox/111.0'
>  Info | 16:19 || Open download folder when finished, is set to: 'True'
>  Info | 16:19 || Downloading files marked as preview, is set to: 'True'
> 
>  WARNING | 16:19 || Previews downloading is enabled; repetitive and/or emoji spammed media might be downloaded!
>  Info | 16:19 || You have launched in Single Post download mode
>                  Please enter the ID of the post you would like to download
>                  After you click on a post, it will show in your browsers url bar
> 
>                  ► Post ID: 510554575002939392
>  Info | 16:20 || Inspecting a post by Tsbellabates
>  Info | 16:20 || Amount of Media linked to Single post: 4 (scrapable: 4)
>  Info | 16:20 || Downloading video '2023-05-04_at_16-05_id_510507960833679360.m3u8'
> start time for stream 1 is not set in estimate_timings_from_pts
> stream 1 : no TS found at start of file, duration not set
> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> sample rate not set
> 
>  [19]ERROR | 16:20 || Unexpected error during sorting Single Post download;
> Traceback (most recent call last):
>   File "C:\Users\***\Videos\fansly-downloader_test\fansly_downloader.py", line 1185, in <module>
>     sort_download(accessible_media)
>   File "C:\Users\***\Videos\fansly-downloader_test\fansly_downloader.py", line 741, in sort_download
>     file_downloaded = download_m3u8(m3u8_url = download_url, save_path = save_path)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\***\Videos\fansly-downloader_test\fansly_downloader.py", line 637, in download_m3u8
>     output_container.mux(packet)
>   File "av\container\output.pyx", line 203, in av.container.output.OutputContainer.mux
>   File "av\container\output.pyx", line 209, in av.container.output.OutputContainer.mux_one
>   File "av\container\output.pyx", line 175, in av.container.output.OutputContainer.start_encoding
>   File "av\container\core.pyx", line 292, in av.container.core.Container.err_check
>   File "av\error.pyx", line 336, in av.error.err_check
> av.error.ValueError: [Errno 22] Invalid argument: 'C:\\Users\\***\\Videos\\fansly-downloader_test\\tsbellabates_fansly\\Videos\\2023-05-04_at_16-05_id_510507960833679360.mp4'; last error log: [mp4] sample rate not set
> 
> 
>  Press Enter to attempt to continue ..

**Comment by Avnsx** [comment]
> av.error.ValueError: [Errno 22] Invalid argument

Unable to reproduce the bug, as the media causing errors appears to be restricted to subscribers only.
To assist in resolving the issue, kindly send an email to ``AvnDev@protonmail.com`` with account credentials, which have access to the mentioned content.

**Comment by CaptainKoons** [comment]
@Avnsx I appreciate your willingness to investigate the issue further. But I hope you understand, that I’m not happy to share my login data online (which would in this case lead to automatically sharing my personal data and credit card details as well).
Hopefully you find a way to solve the issues regardless. 

Thanks in advance & BR!
CK

**Comment by OpenFieldsOfOz** [comment]
I'm seeing this issue on `HotwifeLexiLove`. I'd be happy to send $ via paypal so you can subscribe yourself.

**Comment by Avnsx** [comment]
> I'm seeing this issue on `HotwifeLexiLove`. I'd be happy to send $ via paypal so you can subscribe yourself in order to reproduce.

If you want to help, just create a fresh fansly account, buy a subscription to the mentioned creator and send me the account credentials to ``AvnDev@protonmail.com`` @OpenFieldsOfOz

**Comment by Avnsx** [comment]
Also @OpenFieldsOfOz are you sure that python version 0.4.1 also doesn't fix the issue for you?

**Comment by OpenFieldsOfOz** [comment]
I'm running the `fe25522cfadb397d137b9aa735d0004ec9f05e4b` version from master

**Comment by Avnsx** [comment]
> I'm running the `fe25522cfadb397d137b9aa735d0004ec9f05e4b` version from master

That's not exactly a versioning, just go to the config.ini file and look at the ``version`` string it says there for you

**Comment by OpenFieldsOfOz** [comment]
Yup, version `version = 0.4.1`. Sent you an email with test creds
