### ISSUE TITLE
[Replace with descriptive keypoint title]

### ISSUE THREAD

**Issue by Kroek** [Avnsx/fansly-downloader#123]
## Bug Description
Downloading longer videos results in a memory error

## Actual behavior
the download fails when almost completed, resulting in this error message:

[19]ERROR | 15:31 || Unexpected error during sorting Single Post download;
Traceback (most recent call last):
  File "fansly_downloader.py", line 1188, in <module>
  File "fansly_downloader.py", line 763, in sort_download
MemoryError

for this video, my computer's memory usage only went up to 60%

*( If applicable, [add screenshots](https://stackoverflow.com/a/14494775/15163882) to help explain your problem. )*

## Environment Information
 - Operating System: windows
 - Fansly Downloader Version: v0.4.1
 - Fansly Downloader Type: executable
 - Specific creators name: Boba Bitch

## User Research
*( fill ``[ ]`` with ``x``, if you've already done said task )*

I have done the following:
- [x] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [x] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [x] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

**Comment by Avnsx** [comment]
How much RAM do you have?

**Comment by Kroek** [comment]
I have 16 GB of RAM

it's a .mp4 file

the id is 502723244063731712

that video is 56 minutes long. 
I didn't notice it before, but i did successfully download a 2 and a half hour video so maybe it's not just the length?
